### ISSUE TITLE
Remove deprecated class BaseCheckTestSupport

### ISSUE THREAD

**Issue by subkrish** [checkstyle/checkstyle#4867]
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java

**BaseCheckTestSupport** is now deprecated and longer supported by any of the test classes. 

It must be removed once `xwiki-commons` uses the new `Abstract...TestSupport` classes,  else wercker build will fail as it did in an attempt to remove the class in PR #4655 
https://github.com/checkstyle/checkstyle/pull/4655/files#diff-b05f7d983d1f3ec19e57707a34da40b2
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project xwiki-commons-tool-verification-resources: Compilation failure: Compilation failure:
[ERROR] /pipeline/source/xwiki-commons/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/test/java/org/xwiki/tool/checkstyle/SinceFormatCheckTest.java:[28,39] cannot find symbol
[ERROR] symbol:   class BaseCheckTestSupport
[ERROR] location: package com.puppycrawl.tools.checkstyle
```

**Comment by rnveach** [comment]
> must be removed once xwiki-commons uses the new Abstract...TestSupport classes

xwiki will most likely not update unless we either break their build or send them a PR to force them to change.
@romani Should we send them a PR to force them to change?

**Comment by romani** [comment]
> Should we send them a PR to force them to change?

It would be better to do this, as we know how to do a change. For them it took a while to understand what we did.
@subkrish , can you send PR to xwiki project ? 
looks like we released new TestSupport classes already so they could switch.

**Comment by subkrish** [comment]
@romani @rnveach I just made the PR -> https://github.com/xwiki/xwiki-commons/pull/19 making the necessary changes by updating the Checkstyle version and by removing the test to extend `BaseCheckTestSupport` and to now extend `AbstractModuleTestSupport`.

**Comment by subkrish** [comment]
@romani @rnveach xwiki/xwiki-commons#19 has been merged. I will now remove the BaseCheckTestSupport class as I am pretty sure no other project uses it anymore.

**Comment by romani** [comment]
@subkrish , you can try, as CIs are green we good to merge.

**Comment by romani** [comment]
fix is merged
