### PR TITLE
spelling: code

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

note that this conflicts with #5654 (because there are 2 lines in a row, one's a comment, one's code). It's trivially resolvable. My original commit sequence has this change built on top of that change, but for "independent" (conflicting) PRs, that progression can't be followed.

split from #5647

### CODE REVIEW

**Comment by jsoref** [comment]
I can't see the team city build bits. So I'm not sure what to do here....

I'll wait until some of the dust settles to figure out what to do ...

**Comment by romani** [comment]
from TC:
```
[14:02:12][Step 1/2] [ERROR] COMPILATION ERROR : 
[14:02:12][Step 1/2] [INFO] -------------------------------------------------------------
[14:02:12][Step 1/2] [ERROR] /mnt/agent/work/42b5f8d952debbdf/src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/GeneratedJavadocTokenTypesTest.java:[223,44] cannot find symbol
[14:02:12][Step 1/2]   symbol:   variable RULE_wrongSinletonTag
[14:02:12][Step 1/2]   location: class com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser
[14:02:12][Step 1/2] [INFO] 1 error
```

strange, you did not change this in this PR, this is a change from another PR.
Lets wait some time to let other CIs pass, and we will restart TC.
