### PR TITLE
Issue #18074: Align SLF4J version to the version reflections uses, and mark it as a runtime dependency

### LINKED ISSUE #18074: JAR for 12.1.1 is missing org.slf4j package
The JAR for checkstyle 12.1.1 seems to be missing the `org.slf4j` package which causes it to raise an exception when attempting to run it with the `sarif` output format:

```bash
/code # java -jar /opt/checkstyle/checkstyle.jar -f sarif -c /sun_checks.xml .
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.reflections.Reflections.<clinit>(Reflections.java:115)
	at com.puppycrawl.tools.checkstyle.meta.XmlMetaReader.readAllModulesIncludingThirdPartyIfAny(XmlMetaReader.java:75)
	at com.puppycrawl.tools.checkstyle.SarifLogger.loadModuleMetadata(SarifLogger.java:212)
	at com.puppycrawl.tools.checkstyle.SarifLogger.<init>(SarifLogger.java:188)
	at com.puppycrawl.tools.checkstyle.Main$OutputFormat.createListener(Main.java:588)
	at com.puppycrawl.tools.checkstyle.Main.createListener(Main.java:516)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:421)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:347)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:206)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:130)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more
```
---

Checkstyle 12.1.0:

Image

Checkstyle 12.1.1:

Image

### PR DESCRIPTION
**Pull request by mureinik**
This PR handles a regression introduced by #17958:
As long as `org.slf4j:slf4j-api` was not explicilty stated in the `pom.xml`, the assembly plugin would pick up the transitive dependency.
With #17958, this dependency was explicitly marked as a test dependency, making the assembly plugin skip it. To fix this regression, the dependency was aligned to the version used by `org.reflections:reflections` and marked as a runtime dependency, making it availale for both the tests that use it and the checkstyle-all uberjar.

Fixes #18074

### CODE REVIEW

**Comment by mureinik** [comment]
@romani fix for #18074 is ready. 

Quick analysis of CI failures:
- [Check PR Description / Analyze (pull_request)](https://github.com/checkstyle/checkstyle/actions/runs/19241357583/job/55004588996?pr=18076) fails because the bug is not not approved yet. You tagged me on it, so I assume you wanted me to fix it
- [ci/circleci: no-exception-Pmd-elasticsearch-lombok-ast](https://circleci.com/gh/checkstyle/checkstyle/1128415) fails with the error "org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-pmd-plugin:3.28.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.velocity:velocity-engine-core:jar:2.4". The same script runs just fine on my machine, and this dependency is very much present (see, e.g., https://mvnrepository.com/artifact/org.apache.velocity/velocity-engine-core/2.4). Moreover, this PR does nothing to touch that area. I'm assuming this is a temporary network issue, and this CI step needs to be retriggered.

File: pom.xml [hunk 1]
```diff
@@ -208,7 +208,7 @@
     <pmd.version>7.18.0</pmd.version>
     <maven.jacoco.plugin.version>0.8.14</maven.jacoco.plugin.version>
     <mockito.version>5.2.0</mockito.version>
-    <slf4j.version>2.0.17</slf4j.version>
+    <slf4j.version>1.7.32</slf4j.version> <!-- Aligned with the version reflections depends on -->
```
Comment (romani) [inline pom.xml:211]: Historical context:

https://github.com/checkstyle/checkstyle/commit/981896d54ed2b1e7530c2f7d0e026c315f895ffa#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R264

https://github.com/checkstyle/checkstyle/issues/8742

This deprecated library was used to generate our internal resources during build time, it is not in use in any user visible functionality, so not required in runtime.

So better fix will be to exclude slf4j from such library and use it explicitly or take to it from other transitively.

https://github.com/ronmamo/reflections
https://mvnrepository.com/artifact/org.reflections/reflections

**Review by romani — CHANGES_REQUESTED** [review]
Thanks a lot for quick response.
CI are restarted, all green.

Please consider this comment, I will try to find laptop time to test it.

Extension of CI with few executions will helpful too, to not repeat this problem in future.

File: pom.xml (hunk 1 above)
Comment (mureinik) [reply pom.xml:211]: Sorry, but I'm not sure I understand this comment.

Unless I'm missing something, this library *is* used at runtime, when using the `-f sarif` flag.
Usage chain:
`com.puppycrawl.tools.checkstyle.Main.OutputFormat` instantiates a new `com.puppycrawl.tools.checkstyle.SarifLogger`.
`com.puppycrawl.tools.checkstyle.SarifLogger#loadModuleMetadata` calls `com.puppycrawl.tools.checkstyle.meta.XmlMetaReader#readAllModulesIncludingThirdPartyIfAny`.
`com.puppycrawl.tools.checkstyle.meta.XmlMetaReader#readAllModulesIncludingThirdPartyIfAny` instantiates a new `org.reflections.Reflections` instance.
`org.reflections.Reflections`'s class loading instantiates a static `org.slf4j.Logger` member.

So, IIUC, excluding slf4j from reflections' dependencies won't work.

What am I missing?

Comment (romani) [reply pom.xml:211]: thanks a lot for detailed explanation.

sad, we extended usage of it.
Back in time people from xwiki warned me that it will be problematic dependency.

Ok, PR is good to merge.
